name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: CC=gcc make fetchme
    - name: rebuild
      run: CC=gcc make remove fetchme
    - name: debug
      run: CC=gcc DEBUG=true make remove fetchme
